#!/bin/bash
set -e
wget -q https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip
unzip -o ijava-1.3.0.zip
python3 install.py --sys-prefix
rm -rf ijava-1.3.0.zip install.py java/
